const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, '..', 'data');

// Complete meaning mappings
const meaningFix = {
  // Nouns - complete meanings
  'saya': 'saya',
  'kami': 'kami',
  'anda': 'anda',
  'anda sekalian': 'anda sekalian',
  'orang itu': 'orang itu/dia',
  'orang': 'orang itu/dia',
  'saudara': 'saudara',
  'panggilan': 'panggilan sayang',
  'guru': 'guru',
  'dosen': 'dosen',
  'mahasiswa': 'mahasiswa',
  'pegawai': 'pegawai perusahaan',
  'dokter': 'dokter',
  'universitas': 'universitas',
  'rumah sakit': 'rumah sakit',
  'lampu': 'lampu/listrik',
  'umur': 'umur',
  'buku': 'buku',
  'kamus': 'kamus',
  'majalah': 'majalah',
  'koran': 'koran/surat kabar',
  'buku catatan': 'buku catatan',
  'kartu nama': 'kartu nama',
  'kunci': 'kunci',
  'jam': 'jam',
  'payung': 'payung',
  'tas': 'tas',
  'televisi': 'televisi',
  'kamera': 'kamera',
  'komputer': 'komputer',
  'mobil': 'mobil',
  'meja tulis': 'meja tulis',
  'kursi': 'kursi',
  'bahasa inggris': 'bahasa Inggris',
  'bahasa jepang': 'bahasa Jepang',
  'bahasa': 'bahasa',
  'ruang kelas': 'ruang kelas',
  'ruang makan': 'ruang makan/kantin',
  'kantor': 'kantor',
  'ruang rapat': 'ruang rapat',
  'bagian penerima tamu': 'bagian penerima tamu',
  'ruang tunggu': 'ruang tunggu/lobi',
  'kamar': 'kamar',
  'kamar kecil': 'kamar kecil/toilet',
  'tangga': 'tangga',
  'negara': 'negara',
  'perusahaan': 'perusahaan',
  'rumah': 'rumah',
  'telepon': 'telepon',
  'sepatu': 'sepatu',
  'dasi': 'dasi',
  'anggur': 'anggur',
  'rokok': 'rokok',
  'tempat penjualan': 'tempat penjualan',
  'bawah tanah': 'bawah tanah/basement',
  'lantai': 'lantai/tingkat',
  '100': '100',
  '1000': '1000',
  '10.000': '10.000',
  'lift': 'lift',
  'eskalator': 'eskalator',
  'toko serba ada': 'toko serba ada',
  'bank': 'bank',
  'kantor pos': 'kantor pos',
  'gedung perpustakaan': 'gedung perpustakaan',
  'gedung kesenian': 'gedung kesenian',
  'sekarang': 'sekarang',
  'jam berapa': 'jam berapa',
  'berapa menit': 'berapa menit',
  'A.M': 'A.M (pagi)',
  'P.M': 'P.M (sore/malam)',
  'pagi': 'pagi',
  'siang': 'siang',
  'malam': 'malam',
  '2 hari lalu': '2 hari yang lalu',
  'kemarin': 'kemarin',
  'hari ini': 'hari ini',
  'besok': 'besok',
  'lusa': 'lusa',
  'tadi pagi': 'tadi pagi',
  'nanti malam': 'nanti malam',
  'libur': 'libur/istirahat',
  'istirahat siang': 'istirahat siang',
  'setiap pagi': 'setiap pagi',
  'setiap malam': 'setiap malam',
  'setiap hari': 'setiap hari',
  'hari senin': 'hari Senin',
  'hari selasa': 'hari Selasa',
  'hari rabu': 'hari Rabu',
  'hari kamis': 'hari Kamis',
  'hari jumat': 'hari Jumat',
  'hari sabtu': 'hari Sabtu',
  'hari minggu': 'hari Minggu',
  'hari apa': 'hari apa',
  'nomor': 'nomor',
  'nomor berapa': 'nomor berapa',
  'dari': 'dari ~',
  'sampai': 'sampai ~',
  'dan': '~ dan ~',
  'sekolah': 'sekolah',
  'pasar swalayan': 'pasar swalayan',
  'stasiun': 'stasiun',
  'pesawat terbang': 'pesawat terbang',
  'kapal laut': 'kapal laut',
  'kereta api': 'kereta api',
  'kereta bawah tanah': 'kereta bawah tanah',
  'bis': 'bis',
  'taksi': 'taksi',
  'sepeda': 'sepeda',
  'dengan jalan kaki': 'dengan jalan kaki',
  'orang': 'orang',
  'teman': 'teman',
  'pacar laki-laki': 'pacar laki-laki',
  'pacar perempuan': 'pacar perempuan',
  'keluarga': 'keluarga',
  'sendiri': 'sendiri',
  'minggu lalu': 'minggu lalu',
  'minggu ini': 'minggu ini',
  'minggu depan': 'minggu depan',
  'bulan lalu': 'bulan lalu',
  'bulan ini': 'bulan ini',
  'bulan depan': 'bulan depan',
  'tahun lalu': 'tahun lalu',
  'tahun ini': 'tahun ini',
  'tahun depan': 'tahun depan',
  'bulan': 'bulan',
  'bulan berapa': 'bulan berapa',
  'tanggal': 'tanggal ~',
  'tanggal berapa': 'tanggal berapa',
  'kapan': 'kapan',
  'hari ulang tahun': 'hari ulang tahun',
  'berikutnya': 'berikutnya',
  'nasi': 'nasi',
  'sarapan pagi': 'sarapan pagi',
  'makan siang': 'makan siang',
  'makan malam': 'makan malam',
  'roti': 'roti',
  'telur': 'telur',
  'daging': 'daging',
  'ikan': 'ikan',
  'sayur-sayuran': 'sayur-sayuran',
  'buah-buahan': 'buah-buahan',
  'air': 'air',
  'teh jepang': 'teh Jepang',
  'teh': 'teh',
  'susu': 'susu',
  'jus': 'jus',
  'bir': 'bir',
  'sake': 'sake (arak Jepang)',
  'surat': 'surat',
  'laporan': 'laporan',
  'foto': 'foto',
  'video': 'video',
  'toko': 'toko',
  'halaman': 'halaman',
  'PR': 'PR (pekerjaan rumah)',
  'tenis': 'tenis',
  'sepak bola': 'sepak bola',
  'melihat bunga sakura': 'melihat bunga sakura',
  'rumah': 'rumah',
  'ayah': 'ayah',
  'ibu': 'ibu',
  'kakak laki-laki': 'kakak laki-laki',
  'kakak perempuan': 'kakak perempuan',
  'adik laki-laki': 'adik laki-laki',
  'adik perempuan': 'adik perempuan',
  'anak': 'anak',
  'wanita': 'wanita',
  'pria': 'pria',
  'manusia': 'manusia',
  'tubuh': 'tubuh',
  'kepala': 'kepala',
  'mata': 'mata',
  'telinga': 'telinga',
  'hidung': 'hidung',
  'mulut': 'mulut',
  'gigi': 'gigi',
  'lidah': 'lidah',
  'leher': 'leher',
  'bahu': 'bahu',
  'dada': 'dada',
  'perut': 'perut',
  'punggung': 'punggung',
  'tangan': 'tangan',
  'jari': 'jari',
  'kuku': 'kuku',
  'kaki': 'kaki',
  'lutut': 'lutut',
  'tulang': 'tulang',
  'darah': 'darah',
  'jantung': 'jantung',
  'otak': 'otak',
  'kulit': 'kulit',
  'rambut': 'rambut',
  'wajah': 'wajah',
  'senyum': 'senyum',
  'tawa': 'tawa',
  'air mata': 'air mata',
  'keringat': 'keringat',
  'suara': 'suara',
  'nyanyian': 'nyanyian',
  'lagu': 'lagu',
  'musik': 'musik',
  'tarian': 'tarian',
  'warna': 'warna',
  'merah': 'merah',
  'biru': 'biru',
  'kuning': 'kuning',
  'hijau': 'hijau',
  'ungu': 'ungu',
  'putih': 'putih',
  'hitam': 'hitam',
  'cokelat': 'cokelat',
  'oranye': 'oranye',
  'abu-abu': 'abu-abu',
  'emas': 'emas',
  'perak': 'perak',
  'bentuk': 'bentuk',
  'bulat': 'bulat',
  'segi empat': 'segi empat',
  'segitiga': 'segitiga',
  'bintang': 'bintang',
  'hati': 'hati',
  'size': 'ukuran',
  'besar': 'besar',
  'kecil': 'kecil',
  'panjang': 'panjang',
  'pendek': 'pendek',
  'lebar': 'lebar',
  'sempit': 'sempit',
  'tinggi': 'tinggi',
  'rendah': 'rendah',
  'berat': 'berat',
  'ringan': 'ringan',
  'cepat': 'cepat',
  'lambat': 'lambat',
  'kuat': 'kuat',
  'lemah': 'lemah',
  'keras': 'keras',
  'lunak': 'lunak',
  'panas': 'panas',
  'dingin': 'dingin',
  'hangat': 'hangat',
  'sejuk': 'sejuk',
  'basah': 'basah',
  'kering': 'kering',
  'bersih': 'bersih',
  'kotor': 'kotor',
  'baru': 'baru',
  'lama': 'lama',
  'muda': 'muda',
  'tua': 'tua',
  'bagus': 'bagus',
  'jelek': 'jelek',
  'cantik': 'cantik',
  'tampan': 'tampan',
  ' lucu': 'lucu',
  'serius': 'serius',
  'rajin': 'rajin',
  'malas': 'malas',
  'pandai': 'pandai',
  'bodoh': 'bodoh',
  'kaya': 'kaya',
  'miskin': 'miskin',
  'sakit': 'sakit',
  'sehat': 'sehat',
  'bahagia': 'bahagia',
  'sedih': 'sedih',
  'marah': 'marah',
  'takut': 'takut',
  'malu': 'malu',
  'senang': 'senang',
  'suka': 'suka',
  'benci': 'benci',
  'bosan': 'bosan',
  'semangat': 'semangat',
  'lelah': 'lelah',
  'antusias': 'antusias',
  'sabar': 'sabar',
  'teliti': 'teliti',
  'hati-hati': 'hati-hati',
  'ceroboh': 'ceroboh',
  'berani': 'berani',
  'pengecut': 'pengecut',
  'jujur': 'jujur',
  'pembohong': 'pembohong',
  'ramah': 'ramah',
  'kasar': 'kasar',
  'pendiam': 'pendiam',
  'aktif': 'aktif',
  'supel': 'supel',
  'populer': 'populer',
  'terkenal': 'terkenal',
  'aneh': 'aneh',
  'biasa': 'biasa',
  'istimewa': 'istimewa',
  'lengkap': 'lengkap',
  'cukup': 'cukup',
  'kurang': 'kurang',
  'lebih': 'lebih',
  'paling': 'paling',
  'sama': 'sama',
  'beda': 'beda',
  'mirip': 'mirip',
  'tepat': 'tepat',
  'salah': 'salah',
  'benar': 'benar',
  'pasti': 'pasti',
  'mungkin': 'mungkin',
  'jelas': 'jelas',
  'ragu': 'ragu',
  'yakin': 'yakin',
  'penting': 'penting',
  'tidak penting': 'tidak penting',
  'berguna': 'berguna',
  'percuma': 'percuma',
  'mudah': 'mudah',
  'sulit': 'sulit',
  'gampang': 'gampang',
  'susah': 'susah',
  'sederhana': 'sederhana',
  'rumit': 'rumit',
  'praktis': 'praktis',
  'ribet': 'ribet',
  'nyaman': 'nyaman',
  'tidak nyaman': 'tidak nyaman',
  'aman': 'aman',
  'bahaya': 'bahaya',
  'sepi': 'sepi',
  'ramai': 'ramai',
  'hening': 'hening',
  'berisik': 'berisik',
  'tenang': 'tenang',
  'gelisah': 'gelisah',
  'lega': 'lega',
  'puas': 'puas',
  'kecewa': 'kecewa',
  'bangga': 'bangga',
  'malu': 'malu',
  'terharu': 'terharu',
  'kagum': 'kagum',
  'cemburu': 'cemburu',
  'kasihan': 'kasihan',
  'sayang': 'sayang',
  'rindu': 'rindu',
  'sangat suka': 'sangat suka',
  'sangat benci': 'sangat benci',
  'berbagai macam': 'berbagai macam',
  'macam-macam': 'macam-macam',
  'sia-sia': 'sia-sia',
  'tiba-tiba': 'tiba-tiba',
  'ajaib': 'ajaib',
  'luar biasa': 'luar biasa',
  'hebat': 'hebat',
  'handal': 'handal',
  'andalan': 'andalan',
  'kebanggaan': 'kebanggaan',
  'mengagumkan': 'mengagumkan',
  'menakjubkan': 'menakjubkan',
  'mengerikan': 'mengerikan',
  'menakutkan': 'menakutkan',
  'menyenangkan': 'menyenangkan',
  'membosankan': 'membosankan',
  'menghibur': 'menghibur',
  'mengganggu': 'mengganggu',
  'mengkhawatirkan': 'mengkhawatirkan',
  'memuaskan': 'memuaskan',
  'mengecewakan': 'mengecewakan',
  'menyedihkan': 'menyedihkan',
  'menggembirakan': 'menggembirakan',
  'membingungkan': 'membingungkan',
  'membingungkan': 'membingungkan',
  'mencurigakan': 'mencurigakan',
  'mengesankan': 'mengesankan',
  'mengharukan': 'mengharukan',
  'mengerikan': 'mengerikan',
  'menakutkan': 'menakutkan',
  'menyenangkan': 'menyenangkan',
  'membosankan': 'membosankan',
  'menghibur': 'menghibur',
  'mengganggu': 'mengganggu',
  'mengkhawatirkan': 'mengkhawatirkan',
  'memuaskan': 'memuaskan',
  'mengecewakan': 'mengecewakan',
  'menyedihkan': 'menyedihkan',
  'menggembirakan': 'menggembirakan',
  'membingungkan': 'membingungkan',
  'mencurigakan': 'mencurigakan',
  'mengesankan': 'mengesankan',
  'mengharukan': 'mengharukan'
};

// Fix data file
function fixDataFile(filePath, categoryName) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  let fixed = 0;
  let removed = 0;

  // Fix meanings in all questions
  data.levels.forEach(level => {
    level.questions.forEach(q => {
      // Fix meaning
      const meaning = q.meaning.trim().toLowerCase();
      if (meaningFix[meaning]) {
        q.meaning = meaningFix[meaning];
      }

      // Fix options
      q.options = q.options.map(opt => {
        const optLower = opt.trim().toLowerCase();
        if (meaningFix[optLower]) {
          return meaningFix[optLower];
        }
        return opt;
      });
    });
  });

  // For nouns/verbs/adjectives - remove entries where kanji is same as reading
  // (to avoid duplication with hiragana/katakana quizzes)
  if (categoryName !== 'hiragana' && categoryName !== 'katakana' && categoryName !== 'kanji') {
    data.levels.forEach(level => {
      const originalLength = level.questions.length;
      level.questions = level.questions.filter(q => {
        // Keep if kanji is different from reading (has actual kanji)
        // Or if it's a katakana word
        const isKatakana = /^[\u30A0-\u30FF]+$/.test(q.kanji);
        const hasKanji = q.kanji !== q.reading || isKatakana;
        return hasKanji;
      });
      removed += originalLength - level.questions.length;
    });
  }

  // Regenerate options from same level only
  data.levels.forEach(level => {
    const levelMeanings = level.questions.map(q => q.meaning);

    level.questions.forEach(q => {
      // Get wrong options from same level only
      const otherMeanings = levelMeanings.filter(m => m !== q.meaning);
      const shuffled = otherMeanings.sort(() => 0.5 - Math.random());
      const wrongOptions = shuffled.slice(0, 3);

      // If not enough options from level, add some generic
      if (wrongOptions.length < 3) {
        const generic = ['Makan', 'Minum', 'Tidur', 'Jalan', 'Lari', 'Baca', 'Tulis', 'Duduk', 'Berdiri', 'Pergi'];
        for (const g of generic) {
          if (wrongOptions.length >= 3) break;
          if (g !== q.meaning && !wrongOptions.includes(g)) {
            wrongOptions.push(g);
          }
        }
      }

      const options = [...wrongOptions.slice(0, 3)];
      const correctIndex = Math.floor(Math.random() * 4);
      options.splice(correctIndex, 0, q.meaning);

      q.options = options;
      q.correctIndex = correctIndex;
    });
  });

  fs.writeFileSync(filePath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`${categoryName}: Fixed meanings, removed ${removed} duplicates, regenerated options`);
}

// Fix all files
fixDataFile(path.join(dataDir, 'nouns.json'), 'nouns');
fixDataFile(path.join(dataDir, 'verbs.json'), 'verbs');
fixDataFile(path.join(dataDir, 'adjectives.json'), 'adjectives');
fixDataFile(path.join(dataDir, 'kanji.json'), 'kanji');

console.log('\nAll data files fixed!');
